// Dreizunge headless test runner.
//   node test/run.js            # full suite
//   node test/run.js --quick    # skip the e2e (server-spawning) tests
// Exits non-zero if any step fails.
const cp = require('child_process');
const path = require('path');
const fs = require('fs');
const { summaryLine } = require('./summary.js');

const ROOT = path.join(__dirname, '..');
const quick = process.argv.includes('--quick');

// Counted in run() itself — the single increment site — so the printed total cannot drift from
// the number of steps actually executed. Declared BEFORE run() rather than after: this codebase
// has shipped a TDZ crash before (v68.1), and relying on "the first call happens later" is exactly
// the assumption that broke then.
let total = 0;
const failures = [];

function run(label, cmd, args, opts = {}) {
  total++;
  process.stdout.write(`\n▶ ${label}\n`);
  const r = cp.spawnSync(cmd, args, { cwd: ROOT, stdio: 'inherit', ...opts });
  if (r.status !== 0) { console.error(`✗ ${label} FAILED (exit ${r.status})`); failures.push(label); }
  else console.log(`✓ ${label}`);
}


// 1) Static checks — always run.
run('server.js node --check', 'node', ['--check', path.join(ROOT, 'server.js')]);
run('inline script: index.html', 'node', [path.join(__dirname, 'check-inline.js'), path.join(ROOT, 'index.html')]);
run('structure: no screen nested inside another screen (v69_s2)', 'node', [path.join(__dirname, 'unit-screen-structure.test.js')]);
const docs = path.join(ROOT, 'docs', 'index.html');
if (fs.existsSync(docs)) run('inline script: docs/index.html', 'node', [path.join(__dirname, 'check-inline.js'), docs]);
run('ui.json parses', 'node', ['-e', "require(path.join('" + ROOT.replace(/\\/g, '\\\\') + "','ui.json'));console.log('  ui.json: OK')"]);
run('lessons.json parses', 'node', ['-e', "require(path.join('" + ROOT.replace(/\\/g, '\\\\') + "','lessons.json'));console.log('  lessons.json: OK')"]);
run('harness: lib-dom textContent ordering', 'node', [path.join(__dirname, 'unit-lib-dom-textcontent.test.js')]);

// 2) Unit tests — always run.
run('unit: id-based resolvers (item 2)', 'node', [path.join(__dirname, 'unit-resolvers.test.js')]);
run('unit: arc-mode options (item 3)', 'node', [path.join(__dirname, 'unit-arc-options.test.js')]);
run('unit: arc reinforce types (v46 bug #1)', 'node', [path.join(__dirname, 'unit-arc-reinforce-types.test.js')]);
run('unit: story vocab highlighting respects word boundaries (v73_d)', 'node', [path.join(__dirname, 'unit-vocab-highlight.test.js')]);
run('unit: completion-card lesson icon row (v73_g)', 'node', [path.join(__dirname, 'unit-comp-lesson-icons.test.js')]);
run('unit: a round never asks one question twice (v73_i)', 'node', [path.join(__dirname, 'unit-exercise-qid-unique.test.js')]);
run('unit: QC survives a chapter edited mid-pass (v73_j)', 'node', [path.join(__dirname, 'unit-qc-concurrent-edit.test.js')]);
run('unit: pdf text-span selection', 'node', [path.join(__dirname, 'unit-pdf-selection.test.js')]);
run('unit: conjugation grouping (item 4)', 'node', [path.join(__dirname, 'unit-conjugation-grouping.test.js')]);
run('unit: conjugation distractors are same-verb (v78_d)', 'node', [path.join(__dirname, 'unit-conjugation-distractors.test.js')]);
run('unit: grammar reinforce note (item 5)', 'node', [path.join(__dirname, 'unit-grammar-reinforce.test.js')]);
run('unit: editor sync on delete (item 3)', 'node', [path.join(__dirname, 'unit-editor-sync.test.js')]);
run('unit: tts voice-quality helpers (item 1)', 'node', [path.join(__dirname, 'unit-tts-voice.test.js')]);
run('unit: tts never approximates a missing voice (v55_x)', 'node', [path.join(__dirname, 'unit-tts-no-approximation.test.js')]);
run('unit: an ALL-CAPS word is spoken as a word, not spelled out (item AW, v88_b)', 'node', [path.join(__dirname, 'unit-tts-allcaps.test.js')]);
run('unit: always-on sound-test row (v49)', 'node', [path.join(__dirname, 'unit-tts-test-row.test.js')]);
run('unit: lesson-type meta table (item 8)', 'node', [path.join(__dirname, 'unit-lesson-type-meta.test.js')]);
run('unit: word-count tokenizer (item 8)', 'node', [path.join(__dirname, 'unit-word-count.test.js')]);
run('unit: lesson-row subtitle', 'node', [path.join(__dirname, 'unit-lesson-subtitle.test.js')]);
run('unit: lowercase title + app.motto tagline (v49)', 'node', [path.join(__dirname, 'unit-app-motto.test.js')]);
run('unit: word_forms validator', 'node', [path.join(__dirname, 'unit-word-forms.test.js')]);
run('unit: word_forms client play', 'node', [path.join(__dirname, 'unit-word-forms-client.test.js')]);
run('unit: inflections validator (v82_c)', 'node', [path.join(__dirname, 'unit-inflections.test.js')]);
run('unit: unspaced-script whole-word matching, client/server parity (v82_c)', 'node', [path.join(__dirname, 'unit-unspaced-scripts-parity.test.js')]);
run('unit: synonyms in-context builder', 'node', [path.join(__dirname, 'unit-synonyms.test.js')]);
run('unit: story context + num_ctx sizing per generator (v72_f)', 'node', [path.join(__dirname, 'unit-generation-context.test.js')]);
run('unit: sentence segmentation client/server parity (v72_a)', 'node', [path.join(__dirname, 'unit-sentence-segmentation.test.js')]);
run('unit: synonyms context sentence', 'node', [path.join(__dirname, 'unit-syn-context.test.js')]);
run('unit: syn/antonym prompt states the count (v78_b)', 'node', [path.join(__dirname, 'unit-syn-count.test.js')]);
run('unit: storyline bottom row + re-create wiring', 'node', [path.join(__dirname, 'unit-recreate-ui.test.js')]);
run('unit: chapter navigation (same-language)', 'node', [path.join(__dirname, 'unit-chapter-nav.test.js')]);
run('unit: user-flag editor (correct version + apply)', 'node', [path.join(__dirname, 'unit-user-flag-editor.test.js')]);
run('unit: play-flag target matching', 'node', [path.join(__dirname, 'unit-play-flag.test.js')]);
run('unit: static teacher-mode edit gating', 'node', [path.join(__dirname, 'unit-static-teacher.test.js')]);
run('unit: continue-story language filter', 'node', [path.join(__dirname, 'unit-continue-filter.test.js')]);
run('unit: attribute escaping (escAttr not escHtml)', 'node', [path.join(__dirname, 'unit-attr-escaping.test.js')]);
run('unit: lesson-type build registry (B-phase-1)', 'node', [path.join(__dirname, 'unit-build-registry.test.js')]);
run('unit: renderEx exercise-renderer registry (B-phase-2)', 'node', [path.join(__dirname, 'unit-renderex-registry.test.js')]);
run('unit: lesson-editor registry (B-phase-3)', 'node', [path.join(__dirname, 'unit-editor-registry.test.js')]);
run('unit: add-lesson server registry (B-phase-4)', 'node', [path.join(__dirname, 'unit-add-lesson-registry.test.js')]);
run('unit: per-language prompt examples — 4 prompts + de seed (A)', 'node', [path.join(__dirname, 'unit-prompt-examples.test.js')]);
run('unit: storyline-screen QC button + lesson-types dropdown (v47)', 'node', [path.join(__dirname, 'unit-storyline-screen-extras.test.js')]);
run('unit: static flag hiding + download/submit pill (v47)', 'node', [path.join(__dirname, 'unit-static-flags.test.js')]);
run('unit: import merge mode — flags-only onto existing (v47)', 'node', [path.join(__dirname, 'unit-import-merge.test.js')]);
run('unit: harvest rated items → examples.json (A)', 'node', [path.join(__dirname, 'unit-harvest-examples.test.js')]);
run('unit: mixed-type review lessons (C)', 'node', [path.join(__dirname, 'unit-mixed-lessons.test.js')]);
run('unit: mixed pool rating-aware (v46 #7)', 'node', [path.join(__dirname, 'unit-mixed-rating.test.js')]);
run('unit: static story edit (in-memory save)', 'node', [path.join(__dirname, 'unit-static-story-edit.test.js')]);
run('unit: static summary edit (in-memory save)', 'node', [path.join(__dirname, 'unit-static-summary-edit.test.js')]);
run('unit: summary editor Cancel closes the editor (v79_c)', 'node', [path.join(__dirname, 'unit-summary-edit-cancel.test.js')]);
run('unit: chapter export (error-hunt + meta)', 'node', [path.join(__dirname, 'unit-export-lessons.test.js')]);
run('unit: static client export (eh/aeh + meta)', 'node', [path.join(__dirname, 'unit-client-export.test.js')]);
run('unit: static build markers', 'node', [path.join(__dirname, 'unit-static-markers.test.js')]);
run('unit: generation metadata (_genMeta everywhere)', 'node', [path.join(__dirname, 'unit-genmeta.test.js')]);
run('unit: edit-history report (v46 #12)', 'node', [path.join(__dirname, 'unit-report-edits.test.js')]);
run('unit: chapter-link repair (v46 bug #2)', 'node', [path.join(__dirname, 'unit-chapter-link-repair.test.js')]);
run('unit: storyline lock hardening (v46 bug #2)', 'node', [path.join(__dirname, 'unit-storyline-lock-hardening.test.js')]);
run('unit: japanese furigana paste + tokenizer (v47)', 'node', [path.join(__dirname, 'unit-furigana.test.js')]);
run('unit: intro learn-the-script course (v48)', 'node', [path.join(__dirname, 'unit-intro-script.test.js')]);
run('unit: QC dispatch — synonyms/word_forms (v48)', 'node', [path.join(__dirname, 'unit-qc-dispatch.test.js')]);
run('unit: QC skip already-checked lessons (v49 bug 6)', 'node', [path.join(__dirname, 'unit-qc-skip.test.js')]);
run('unit: static version derived from server APP_VERSION (v49)', 'node', [path.join(__dirname, 'unit-version-derivation.test.js')]);
run('unit: current roadmap names the current line (v78_b)', 'node', [path.join(__dirname, 'unit-roadmap-version.test.js')]);
run('unit: docs/ built from current sources (v73_b)', 'node', [path.join(__dirname, 'unit-static-freshness.test.js')]);
run('unit: static build bakes CP1/CP2 analysis (text explorer offline, v86_z)', 'node', [path.join(__dirname, 'unit-static-analysis-bake.test.js')]);
run('unit: runner reports its own check count (v70)', 'node', [path.join(__dirname, 'unit-run-summary.test.js')]);
run('unit: translate-ui discovers every offered language (v53)', 'node', [path.join(__dirname, 'unit-translate-ui-langs.test.js')]);
run('unit: llm.js race guard clears its timer (v53_c)', 'node', [path.join(__dirname, 'unit-llm-timeout-handle.test.js')]);
run('unit: storyline summary model log + stamp (v53_c)', 'node', [path.join(__dirname, 'unit-storyline-summary-stamp.test.js')]);
run('unit: story provenance stamp + buildGenMeta model required (v53_d)', 'node', [path.join(__dirname, 'unit-story-stamp.test.js')]);
run('unit: translation provenance stamp (v55_f)', 'node', [path.join(__dirname, 'unit-translation-stamp.test.js')]);
run('unit: QC for generated texts — correct + guard (v55_g)', 'node', [path.join(__dirname, 'unit-qc-correct.test.js')]);
run('unit: collapsible model popover (v55_o)', 'node', [path.join(__dirname, 'unit-model-popover.test.js')]);
run('unit: added lesson records its difficulty (v56)', 'node', [path.join(__dirname, 'unit-lesson-difficulty.test.js')]);
run('unit: static landing parity — storyboard+summary (v55_p)', 'node', [path.join(__dirname, 'unit-static-landing-parity.test.js')]);
run('unit: identical source/target ratio rule, corpus-calibrated (v53_g)', 'node', [path.join(__dirname, 'unit-identical-ratio.test.js')]);
run('unit: drill lessons — review my mistakes (v54)', 'node', [path.join(__dirname, 'unit-drill.test.js')]);
run('unit: storyline SVG storyboard (v55)', 'node', [path.join(__dirname, 'unit-storyboard.test.js')]);
run('unit: storyboard panels → lesson navigation (v57)', 'node', [path.join(__dirname, 'unit-storyboard-nav.test.js')]);
run('unit: provenance fields — source + createdBy (v58)', 'node', [path.join(__dirname, 'unit-provenance-fields.test.js')]);
run('unit: stampUpdated — same-millisecond save collision', 'node', [path.join(__dirname, 'unit-stamp-updated.test.js')]);
run('unit: cumulative token usage — meter + attribution (v59)', 'node', [path.join(__dirname, 'unit-token-usage.test.js')]);
run('unit: learner navigation + completion card (v60)', 'node', [path.join(__dirname, 'unit-learner-nav.test.js')]);
run('unit: reasoning-model safety — think:false on prose/JSON gen (v60.5)', 'node', [path.join(__dirname, 'unit-reasoning-model-safety.test.js')]);
run('unit: story-translation toggle in read-story panels (v60.6)', 'node', [path.join(__dirname, 'unit-story-translation-toggle.test.js')]);
run('unit: per-role reasoning toggle (v60.7)', 'node', [path.join(__dirname, 'unit-reasoning-toggle.test.js')]);
run('unit: clean card + coverage threshold gate (v60.8)', 'node', [path.join(__dirname, 'unit-coverage-threshold.test.js')]);
run('unit: persistent tutor widget (v62)', 'node', [path.join(__dirname, 'unit-tutor.test.js')]);
run('unit: tutor retrieval — spoiler-safe + scoped (v62)', 'node', [path.join(__dirname, 'unit-tutor-retrieval.test.js')]);
run('unit: tutor streaming replies (v64)', 'node', [path.join(__dirname, 'unit-tutor-streaming.test.js')]);
run('unit: select story text → ask the tutor (PLAN §12, v83_b)', 'node', [path.join(__dirname, 'unit-tutor-selection.test.js')]);
run('unit: tutor "I have an answer" badge (v84_g)', 'node', [path.join(__dirname, 'unit-tutor-reply-badge.test.js')]);
run('unit: learner accounts + server-side state (v65)', 'node', [path.join(__dirname, 'unit-learners.test.js')]);
run('unit: TLS warning predicates + wiring (v70_b)', 'node', [path.join(__dirname, 'unit-tls-transport.test.js')]);
run('unit: lesson-id integrity (v67.1)', 'node', [path.join(__dirname, 'unit-lesson-id-integrity.test.js')]);
run('unit: provenance-stamp source heal (v68.1)', 'node', [path.join(__dirname, 'unit-meta-source-heal.test.js')]);
run('unit: student-mode flagging + flag-mode stamps (v68.1)', 'node', [path.join(__dirname, 'unit-student-flags.test.js')]);
run('unit: deterministic PDF/text-upload cleanup (v68.1)', 'node', [path.join(__dirname, 'unit-pdf-cleanup.test.js')]);
run('unit: sentence-based PDF chunking (v70_k)', 'node', [path.join(__dirname, 'unit-pdf-chunking.test.js')]);
run('unit: PDF paragraph detection from geometry (v71_b)', 'node', [path.join(__dirname, 'unit-pdf-paragraphs.test.js')]);
run('unit: LLM chapter split contract (v71_b)', 'node', [path.join(__dirname, 'unit-chapter-split.test.js')]);
run('unit: typed-answer letter diff (v71_c)', 'node', [path.join(__dirname, 'unit-typed-diff.test.js')]);
run('unit: vocab article symmetry (v71_d)', 'node', [path.join(__dirname, 'unit-vocab-articles.test.js')]);
run('unit: replay focuses on unsolved questions (v71_f)', 'node', [path.join(__dirname, 'unit-replay-focus.test.js')]);
run('unit: replay targets the least-covered lesson (v78_l)', 'node', [path.join(__dirname, 'unit-replay-target.test.js')]);
run('unit: §0d card items — quit target, post bars, replay (v78_n)', 'node', [path.join(__dirname, 'unit-card-0d.test.js')]);
run('unit: comprehension is gated by the story, not gating it (v71_s)', 'node', [path.join(__dirname, 'unit-comprehension-gate.test.js')]);
run('unit: article choices derived from data, not a table (v71_x)', 'node', [path.join(__dirname, 'unit-article-choices.test.js')]);
run('unit: diacritic QC — scan generates candidates, model decides (v72)', 'node', [path.join(__dirname, 'unit-diacritic-qc.test.js')]);
run('unit: story context sizing + chain budget (v71_t)', 'node', [path.join(__dirname, 'unit-story-context.test.js')]);
run('unit: error-hunt / pass-mark interaction (v71_g)', 'node', [path.join(__dirname, 'unit-errorhunt-passmark.test.js')]);
run('unit: completion-card consistency + drill card removal (v71_h)', 'node', [path.join(__dirname, 'unit-card-consistency.test.js')]);
run('unit: progress-card swallowed errors are visible (v77_b)', 'node', [path.join(__dirname, 'unit-card-errors.test.js')]);
run('unit: mixed-driven story unlock is reachable by playing (v77_c)', 'node', [path.join(__dirname, 'unit-mixed-unlock-reachable.test.js')]);
run('unit: story-finished card — the last page of the walk (v77_f)', 'node', [path.join(__dirname, 'unit-story-finished.test.js')]);
run('unit: story-summary card — the first page of the walk (v77_h)', 'node', [path.join(__dirname, 'unit-story-summary.test.js')]);
run('unit: progress + entry card nav/bars popups (v83_c/v83_d)', 'node', [path.join(__dirname, 'unit-progress-card-nav.test.js')]);
run('unit: story-panel border colour, red→green with comprehension progress (v83_g)', 'node', [path.join(__dirname, 'unit-story-border-color.test.js')]);
run('unit: retranslate a story on demand, after a manual fix (v86_w)', 'node', [path.join(__dirname, 'unit-retranslate-story.test.js')]);
run('unit: retranslate ALL chapters from the storyline page (v86_y)', 'node', [path.join(__dirname, 'unit-retranslate-chain.test.js')]);
run('unit: PLAN §7.0 CP1 — canonical text + analysis records, report-only', 'node', [path.join(__dirname, 'unit-canonical-text.test.js')]);
run('unit: install.sh — one-line local installer, idempotent and non-destructive', 'node', [path.join(__dirname, 'unit-install-script.test.js')]);
run('unit: bin/dreizunge — PATH launcher, symlink resolution + real end-to-end run', 'node', [path.join(__dirname, 'unit-dreizunge-launcher.test.js')]);
run('unit: UI journey transitions (PLAN §C0.1)', 'node', [path.join(__dirname, 'unit-ui-journeys.test.js')]);
run('unit: language picker sync, generation screen <-> library (PLAN §C5)', 'node', [path.join(__dirname, 'unit-lang-picker-sync.test.js')]);
run('unit: static build hides library "Generate new" button (v81_x)', 'node', [path.join(__dirname, 'unit-static-gen-btn-hidden.test.js')]);
run('unit: static build wires tap-to-advance on story text (v86_h)', 'node', [path.join(__dirname, 'unit-static-story-tap-parity.test.js')]);
run('unit: showToast() null-guard checks the right variable (v86_i)', 'node', [path.join(__dirname, 'unit-show-toast-guard.test.js')]);
run('unit: Settings Card shell (PLAN §C4 stage 1)', 'node', [path.join(__dirname, 'unit-settings-card.test.js')]);
run('unit: global mute-pill consolidation (PLAN §C4 "keep going")', 'node', [path.join(__dirname, 'unit-mute-consolidation.test.js')]);
run('unit: lang-pair arrow control (PLAN §C4 acceptance detail)', 'node', [path.join(__dirname, 'unit-lang-pair-arrow.test.js')]);
run('unit: speech icon consistency, read-aloud vs mute (user follow-up)', 'node', [path.join(__dirname, 'unit-speech-icon-consistency.test.js')]);
run('unit: UI language decoupled from "I speak" (user follow-up)', 'node', [path.join(__dirname, 'unit-ui-lang-decouple.test.js')]);
run('unit: speech-mismatch status pill (PLAN §C4 last acceptance detail)', 'node', [path.join(__dirname, 'unit-speech-mismatch-pill.test.js')]);
run('unit: word gate on the story unlock (v81_a, TRACK T)', 'node', [path.join(__dirname, 'unit-word-gate.test.js')]);
run('unit: chapter icon row on the cards (v80_z)', 'node', [path.join(__dirname, 'unit-chapter-icons.test.js')]);
run('unit: lesson-set storyline link (v80_x)', 'node', [path.join(__dirname, 'unit-lessonset-storyline-link.test.js')]);
run('unit: tap a word to enter the lesson flow (v80_t, TRACK T)', 'node', [path.join(__dirname, 'unit-tap-word.test.js')]);
run('unit: story panel states + asked underline (v80_r, TRACK T)', 'node', [path.join(__dirname, 'unit-story-panel-states.test.js')]);
run('unit: per-word progress collector (v80_q, TRACK T)', 'node', [path.join(__dirname, 'unit-word-progress.test.js')]);
run('unit: the observations log + shadow BKT write path (v81_j/l, PLAN §8/B1/B4)', 'node', [path.join(__dirname, 'unit-observations-log.test.js')]);
run('unit: target-language skill registry (v81_k, PLAN §8/B2)', 'node', [path.join(__dirname, 'unit-skill-registry.test.js')]);
run('unit: BKT shadow calculation (v81_l, PLAN §8/B4)', 'node', [path.join(__dirname, 'unit-bkt-shadow.test.js')]);
run('unit: question navigation — back/next (v80_p, §0h)', 'node', [path.join(__dirname, 'unit-question-nav.test.js')]);
run('unit: storyline title placeholder (v80_l, PLAN 9c)', 'node', [path.join(__dirname, 'unit-storyline-title-auto.test.js')]);
run('unit: vocab prompt article rule (v80_j, PLAN F3)', 'node', [path.join(__dirname, 'unit-prompt-article-rule.test.js')]);
run('unit: lesson ids unique within a topic (v80_i)', 'node', [path.join(__dirname, 'unit-lesson-id-unique.test.js')]);
run('unit: lesson output carries the target script (v80_h)', 'node', [path.join(__dirname, 'unit-lesson-script-output.test.js')]);
run('unit: word_forms blank position (v80_g, PLAN F2)', 'node', [path.join(__dirname, 'unit-word-forms-defects.test.js')]);
run('unit: one starter card per chapter (v80_e, was v77_i)', 'node', [path.join(__dirname, 'unit-next-chapter-entry.test.js')]);
run('unit: story-unlocked page — the third page of the walk (v77_j)', 'node', [path.join(__dirname, 'unit-story-unlocked-page.test.js')]);
run('unit: comprehension repeat asks only what is left (v77_t)', 'node', [path.join(__dirname, 'unit-comprehension-repeat.test.js')]);
run('unit: apostrophe forms match in vocabulary highlighting (v77_u)', 'node', [path.join(__dirname, 'unit-apostrophe-match.test.js')]);
run('unit: story is read aloud when it unlocks (v77_v)', 'node', [path.join(__dirname, 'unit-story-autoread.test.js')]);
run('unit: chapter-title pair arrays + math order presentation (v77_x)', 'node', [path.join(__dirname, 'unit-v77x-fixes.test.js')]);
run('unit: round length not padded with repeats (v71_i)', 'node', [path.join(__dirname, 'unit-round-length.test.js')]);
run('unit: model settings — tutor thinking, threads, reveal text (v71_q)', 'node', [path.join(__dirname, 'unit-model-settings.test.js')]);
run('unit: add lessons — shared type picker, add not replace (v71_p)', 'node', [path.join(__dirname, 'unit-add-lessons.test.js')]);
run('unit: drill ledger — mistakes decay, reviews record nothing (v71_n)', 'node', [path.join(__dirname, 'unit-drill-ledger.test.js')]);
run('unit: comprehension lesson type — story questions (v71_l)', 'node', [path.join(__dirname, 'unit-comprehension.test.js')]);
run('unit: {lang} placeholder grammar (v71_d)', 'node', [path.join(__dirname, 'unit-lang-placeholder.test.js')]);
run('unit: no verbatim-English fallbacks in translations (v71_k)', 'node', [path.join(__dirname, 'unit-ui-verbatim-en.test.js')]);
run('unit: every t() key exists in ui.json en (v75_b)', 'node', [path.join(__dirname, 'unit-ui-key-exists.test.js')]);
run('unit: every language is offered in both menus (v76_b)', 'node', [path.join(__dirname, 'unit-lang-menu-coverage.test.js')]);
run('unit: add-lesson menus offer the full suite (v78_j)', 'node', [path.join(__dirname, 'unit-add-lesson-menu.test.js')]);
run('unit: storyline chains survive the language filter (v76_e)', 'node', [path.join(__dirname, 'unit-storyline-lang-filter.test.js')]);
run('unit: script choice declared + corpus stamped (v76_g)', 'node', [path.join(__dirname, 'unit-script-choice.test.js')]);
run('unit: script lessons for a digraphic source (v78_g)', 'node', [path.join(__dirname, 'unit-script-digraphic.test.js')]);
run('unit: script picker + inheritance (v76_i)', 'node', [path.join(__dirname, 'unit-script-picker.test.js')]);
run('unit: continue-story pin survives filters (v76_j)', 'node', [path.join(__dirname, 'unit-continue-pin.test.js')]);
run('unit: docs/ storyline survives the language filter (v76_k)', 'node', [path.join(__dirname, 'unit-static-storyline-filter.test.js')]);
run('unit: translate-ui --langnames request path (v76_c)', 'node', [path.join(__dirname, 'unit-langnames.test.js')]);
run('unit: correct answer advances after the read-out (v75_h)', 'node', [path.join(__dirname, 'unit-speak-advance.test.js')]);
run('unit: word-tap double-render no longer races two auto-speak timers (v85_s)', 'node', [path.join(__dirname, 'unit-word-tap-speech-race.test.js')]);
run('unit: inflection_form answer speaks in the source language (v82_d)', 'node', [path.join(__dirname, 'unit-inflection-speak-lang.test.js')]);
run('unit: coverage-driven mixed round + drill credit-back (v69.1)', 'node', [path.join(__dirname, 'unit-mixed-coverage-round.test.js')]);
run('unit: ui translation QC (validator + translate-ui --qc) (v69_f)', 'node', [path.join(__dirname, 'unit-ui-qc.test.js')]);
run('unit: error-hunt validation + retry (v69_g)', 'node', [path.join(__dirname, 'unit-error-hunt-validation.test.js')]);
run('unit: knowledge-aware round composition (v69_h)', 'node', [path.join(__dirname, 'unit-round-composition.test.js')]);
// Executes the client's render paths in a stub DOM — the only guard that catches TDZ crashes and
// undefined references, which source-level assertions provably cannot see (v69_k).
run('unit: one definition of chapter-complete (v69_l)', 'node', [path.join(__dirname, 'unit-chapter-complete.test.js')]);
run('unit: chapter-level clear progress (v78_e)', 'node', [path.join(__dirname, 'unit-chapter-clear-progress.test.js')]);
run('unit: teacher-mode switch on every page (v78_f)', 'node', [path.join(__dirname, 'unit-teacher-toggle.test.js')]);
run('unit: story highlight — all word sources, two shades (v78_h)', 'node', [path.join(__dirname, 'unit-story-highlight-sources.test.js')]);
run('unit: story panels aligned — renderStoryText joins _storyWordSources (v82_c)', 'node', [path.join(__dirname, 'unit-story-panel-alignment.test.js')]);
run('unit: highlight splits multi-token entries (v78_k)', 'node', [path.join(__dirname, 'unit-highlight-split.test.js')]);
run('unit: multi-chapter job carries the chosen script (v78_p)', 'node', [path.join(__dirname, 'unit-book-script.test.js')]);
run('unit: difficulty-tiered furigana density, restored', 'node', [path.join(__dirname, 'unit-furigana-difficulty.test.js')]);
run('unit: script pin reaches every target-text prompt (v79_f)', 'node', [path.join(__dirname, 'unit-script-pin-coverage.test.js')]);
run('unit: script-primer glyph card — layout, speech, badge (v79_g)', 'node', [path.join(__dirname, 'unit-intro-glyph-card.test.js')]);
run('unit: storyline add-lessons offers the script lesson (v79_h)', 'node', [path.join(__dirname, 'unit-storyline-script-lesson.test.js')]);
run('unit: word-forms distractors must be wrong without the story (v79_i)', 'node', [path.join(__dirname, 'unit-word-forms-decidable.test.js')]);
run('unit: editing controls key on teacher mode alone (v79_j)', 'node', [path.join(__dirname, 'unit-can-edit-teacher-mode.test.js')]);
run('unit: forked storylines — full branch, title marker, both-way switch (v79_k)', 'node', [path.join(__dirname, 'unit-fork-display.test.js')]);
run('unit: chosen speech voice persists across lessons (v79_l)', 'node', [path.join(__dirname, 'unit-tts-voice-persistence.test.js')]);
run('unit: no voiceless utterance while voices load (v79_m)', 'node', [path.join(__dirname, 'unit-tts-voices-not-loaded.test.js')]);
run('unit: storyline/chapter speech locale (v79_n)', 'node', [path.join(__dirname, 'unit-speech-locale.test.js')]);
run('unit: static overrides keep the TTS refresh (v79_p)', 'node', [path.join(__dirname, 'unit-static-selectlang-tts.test.js')]);
run('unit: script pick survives re-selection (v78_q)', 'node', [path.join(__dirname, 'unit-script-pick-persist.test.js')]);
run('unit: continuation post-pass context + no overwrite (v78_r)', 'node', [path.join(__dirname, 'unit-continuation-postpass.test.js')]);
run('smoke: render paths execute (buildPath/storyline/complete/renderEx)', 'node', [path.join(__dirname, 'smoke-render.test.js')]);
run('unit: beginner-mode exercise types (v69.2)', 'node', [path.join(__dirname, 'unit-beginner-types.test.js')]);
run('unit: sentence-ordering length gate (max 5 words)', 'node', [path.join(__dirname, 'unit-order-sentence-length.test.js')]);
run('unit: crossword layout engine (v70_c)', 'node', [path.join(__dirname, 'unit-crossword-layout.test.js')]);
run('unit: stable per-question IDs (qid) — Commit A', 'node', [path.join(__dirname, 'unit-qid-stability.test.js')]);
run('unit: coverage model (fraction/assembly/complete) — Commit B', 'node', [path.join(__dirname, 'unit-coverage.test.js')]);
run('unit: coverage counts source items, not questions (v74_c)', 'node', [path.join(__dirname, 'unit-coverage-item-model.test.js')]);
run('unit: storyline progress is identical in live and static (v74_i)', 'node', [path.join(__dirname, 'unit-live-static-progress-parity.test.js')]);
run('unit: TTS voice ranking — locale before quality (v74_j)', 'node', [path.join(__dirname, 'unit-tts-voice-ranking.test.js')]);
run('unit: TTS voice fallback — device locale when the requested one is absent (v79_d)', 'node', [path.join(__dirname, 'unit-tts-voice-fallback.test.js')]);
run('unit: story-unlocked card — label, prose story, Next-only (v74_l)', 'node', [path.join(__dirname, 'unit-story-unlocked-card.test.js')]);
run('unit: learned-vocab ledger + my-story wiring (v50)', 'node', [path.join(__dirname, 'unit-learned-vocab.test.js')]);
run('unit: my-story generation plumbing (v50)', 'node', [path.join(__dirname, 'unit-my-story.test.js')]);
run('unit: dialect glossary importer (M1, deterministic)', 'node', [path.join(__dirname, 'unit-dialect-glossary.test.js')]);
run('unit: dialect TTS approximate detection (M1)', 'node', [path.join(__dirname, 'unit-dialect-tts.test.js')]);
  run('unit: dialect import panel toggle (M1)', 'node', [path.join(__dirname, 'unit-dialect-panel.test.js')]);
  run('unit: dialect story generator + gate (M2)', 'node', [path.join(__dirname, 'unit-dialect-story.test.js')]);
  run('unit: dialect mute + no-lang prompt', 'node', [path.join(__dirname, 'unit-dialect-mute.test.js')]);
run('unit: no-keyboard glyph ordering (v48)', 'node', [path.join(__dirname, 'unit-no-keyboard.test.js')]);
run('unit: speech-recognition answer checking (v84_g)', 'node', [path.join(__dirname, 'unit-speech-recognition.test.js')]);
run('unit: mic starts off, re-mutes every lesson (v85_b)', 'node', [path.join(__dirname, 'unit-mic-lesson-reset.test.js')]);
run('unit: bottom-bar hide/show toggle (v85_b)', 'node', [path.join(__dirname, 'unit-bottom-bar-toggle.test.js')]);
run('unit: generator-page wizard shell (PLAN §13 milestone 1, v85_c)', 'node', [path.join(__dirname, 'unit-gen-wizard.test.js')]);
run('unit: per-chapter lesson-type override (PLAN §13 milestone 3, v85_f)', 'node', [path.join(__dirname, 'unit-per-chapter-types.test.js')]);
run('unit: post-generation storyboard/QC toggles (PLAN §13 milestone 4, v85_g)', 'node', [path.join(__dirname, 'unit-post-gen-features.test.js')]);
run('unit: generation-time attribution fields (PLAN §13 milestone 5, v85_i)', 'node', [path.join(__dirname, 'unit-gen-attribution.test.js')]);
run('unit: comic upload + panel-drawing UI (PLAN §2.4 Track A4 milestone 1, v85_j)', 'node', [path.join(__dirname, 'unit-comic-panel-ui.test.js')]);
run('unit: comic panel batch extraction, client side (PLAN §2.4 Track A4 milestone 2, v85_k)', 'node', [path.join(__dirname, 'unit-comic-extraction.test.js')]);
run('unit: storyline artwork — comic images vs storyboard (user request)', 'node', [path.join(__dirname, 'unit-storyline-artwork.test.js')]);
run('unit: storyline chapter management — reorder/split/add (user request)', 'node', [path.join(__dirname, 'unit-storyline-chapters.test.js')]);
run('unit: comic chapter formation, client side (PLAN §2.4 Track A4 milestone 3, v85_m)', 'node', [path.join(__dirname, 'unit-comic-chapter.test.js')]);
run('unit: comic text review card — edit/confirm before lesson generation (v86_v)', 'node', [path.join(__dirname, 'unit-comic-review-card.test.js')]);
run('unit: post-gen storyboard opt-in fix, client side (v85_p)', 'node', [path.join(__dirname, 'unit-postgen-storyboard-optin.test.js')]);
run('unit: post-gen analysis opt-in, client side, mirrors postGenStoryboard (item W follow-up, v86_o)', 'node', [path.join(__dirname, 'unit-postgen-analysis-optin.test.js')]);
run('unit: comic story-panel progress-card rendering (PLAN §2.4 Track A4 milestone 4, v85_n)', 'node', [path.join(__dirname, 'unit-comic-story-panel.test.js')]);
run('unit: comic panel auto-detection, client side (PLAN §2.4 Track A4 milestone 5, v85_o)', 'node', [path.join(__dirname, 'unit-comic-detect.test.js')]);
run('unit: hidden lessons omitted/non-blocking in static (v48)', 'node', [path.join(__dirname, 'unit-hidden-lessons.test.js')]);
run('unit: inline onclick escaping (read-story SyntaxError)', 'node', [path.join(__dirname, 'unit-inline-escaping.test.js')]);
run('unit: error-hunt content-aware RTL', 'node', [path.join(__dirname, 'unit-error-hunt-rtl.test.js')]);
run('unit: order-exercise RTL keying (v49)', 'node', [path.join(__dirname, 'unit-order-rtl.test.js')]);
run('unit: word_forms/synonyms content-aware RTL (v49)', 'node', [path.join(__dirname, 'unit-wordforms-syn-rtl.test.js')]);
run('unit: stripThink reasoning-model hardening', 'node', [path.join(__dirname, 'unit-strip-think.test.js')]);
run('unit: model-picker wiring + static-exclusion', 'node', [path.join(__dirname, 'unit-model-picker.test.js')]);
run('unit: parseTableLesson non-ASCII header regression', 'node', [path.join(__dirname, 'unit-table-lesson.test.js')]);
run('unit: close-lang-pairs identical-field gating', 'node', [path.join(__dirname, 'unit-close-lang-pairs.test.js')]);
run('unit: dialect + synonyms prompt strictness', 'node', [path.join(__dirname, 'unit-prompt-strictness.test.js')]);
run('unit: QC editor model-aware label', 'node', [path.join(__dirname, 'unit-qc-editor-label.test.js')]);
run('unit: QC collect-and-compare per model', 'node', [path.join(__dirname, 'unit-qc-collect.test.js')]);
run('unit: feedback animations + mixed source icons', 'node', [path.join(__dirname, 'unit-ui-feedback-mixed-icons.test.js')]);
run('unit: storyline theme by story style', 'node', [path.join(__dirname, 'unit-storyline-theme.test.js')]);
run('unit: PLAN §7.0 CP1/CP2, item W step 4 — text explorer client fetch/render logic', 'node', [path.join(__dirname, 'unit-text-explorer.test.js')]);
run('unit: item W follow-up — analyzeChaptersRun() batch curator trigger (v86_p)', 'node', [path.join(__dirname, 'unit-analyze-chapters-run.test.js')]);
run('unit: lesson-set card story display — language flags + text explorer (v86_ad)', 'node', [path.join(__dirname, 'unit-lesson-set-story-explorer.test.js')]);
run('unit: jobs popover — tutor synthetic entry + stacking-context fix (item U follow-up)', 'node', [path.join(__dirname, 'unit-jobs-popover.test.js')]);
run('unit: synchronous LLM routes are visible in the jobs popover (item AT, v88_b)', 'node', [path.join(__dirname, 'unit-jobs-sync-inflight.test.js')]);
run('unit: unfinished-project drafts — client-side half (item R)', 'node', [path.join(__dirname, 'unit-drafts.test.js')]);
run('unit: unfinished-project drafts — comic upload flow, client-side half (item R follow-up)', 'node', [path.join(__dirname, 'unit-drafts-comic.test.js')]);

// 3) E2E — spawn the real server + fake Ollama. Skipped with --quick.
if (!quick) {
  run('e2e: skill registry API (v81_k, PLAN §8/B2)', 'node', [path.join(__dirname, 'unit-skill-registry-api.test.js')]);
  run('e2e: vocabulary skill tagging (v81_k, PLAN §8/B3)', 'node', [path.join(__dirname, 'e2e-skill-tagging.test.js')]);
  run('e2e: PLAN §7.0 CP2 — lemma/form/phrase/sense/frequency/script analysis via a real (fake) LLM call', 'node', [path.join(__dirname, 'unit-canonical-analysis.test.js')]);
  run('e2e: PLAN §7.0 CP3 — proposed curriculum plan (concepts/prerequisites/ordering), report-only', 'node', [path.join(__dirname, 'unit-curriculum-plan.test.js')]);
  run('e2e: PLAN §7.0 CP4 — vocabulary lesson through the existing contract, validated via real buildStandardExercises', 'node', [path.join(__dirname, 'unit-curriculum-lesson.test.js')]);
  run('e2e: PLAN §7.0 CP5 — silent shadow-mode consumption of the curriculum plan (progress card unchanged)', 'node', [path.join(__dirname, 'unit-cp5-shadow.test.js')]);
  run('e2e: PLAN §7.0 CP1/CP2, item W step 2-3 — background analysis job + per-chapter cache + GET shadow', 'node', [path.join(__dirname, 'e2e-analysis.test.js')]);
  run('e2e: llm.js warmup() sends think:false on the wire (v83_r)', 'node', [path.join(__dirname, 'e2e-warmup-think.test.js')]);
  run('e2e: PWA install support -- manifest/sw/icon served, shell-only interception (v84_b)', 'node', [path.join(__dirname, 'e2e-pwa-install.test.js')]);
  run('e2e: PLAN §7.0 apply-cp-lessons.js — additive CP1-4 lesson writes, cross-chapter dedup', 'node', [path.join(__dirname, 'unit-apply-cp-lessons.test.js')]);
  // Moved inside the block in v70_b: these six spawn a real server + fake Ollama, but were
  // registered outside it, so --quick spawned servers despite this file's header promising
  // it skips them. The promise now holds.
  run('e2e: mixed lesson edit (type round-trip)', 'node', [path.join(__dirname, 'e2e-mixed-lesson-edit.test.js')]);
  run('e2e: every lesson type survives an edit round-trip (v75_e)', 'node', [path.join(__dirname, 'e2e-lesson-edit-roundtrip.test.js')]);
  run('e2e: flagged merge-import keeps storyline storyboards (v75_f)', 'node', [path.join(__dirname, 'e2e-import-storyboard.test.js')]);
  run('e2e: rating/flag round-trip (v46 Tier 1)', 'node', [path.join(__dirname, 'e2e-rating-edit.test.js')]);
  run('e2e: pass mark per storyline + chapter (v69_i)', 'node', [path.join(__dirname, 'e2e-pass-mark.test.js')]);
  run('e2e: model text cleanup — deletion-only (v69_m)', 'node', [path.join(__dirname, 'e2e-text-cleanup.test.js')]);
  run('e2e: teacher dashboard — overview + flag triage (v69_n)', 'node', [path.join(__dirname, 'e2e-teacher-dashboard.test.js')]);
  run('e2e: book chapters sharing a title stay distinct (v69_q)', 'node', [path.join(__dirname, 'e2e-book-duplicate-titles.test.js')]);
  run('e2e: insecure-transport warning (v70_b)', 'node', [path.join(__dirname, 'e2e-tls-warning.test.js')]);
  run('e2e: generate-book + storyline-title (item 5)', 'node', [path.join(__dirname, 'e2e-generate.test.js')]);
  run('e2e: userPrompt stores full input', 'node', [path.join(__dirname, 'e2e-userprompt.test.js')]);
  run('e2e: dialect glossary import (M1)', 'node', [path.join(__dirname, 'e2e-dialect-import.test.js')]);
  run('e2e: bookjob continuation + arc lessons', 'node', [path.join(__dirname, 'e2e-bookjob.test.js')]);
  run('e2e: book arc honours the ticked lesson types (v71_u)', 'node', [path.join(__dirname, 'e2e-book-arc-types.test.js')]);
  run('e2e: book formats — picker/route parity incl. all_types (v68.1)', 'node', [path.join(__dirname, 'e2e-book-formats.test.js')]);
  run('e2e: book topic not truncated', 'node', [path.join(__dirname, 'e2e-booktopic.test.js')]);
  run('e2e: ui.json hot-reload', 'node', [path.join(__dirname, 'e2e-ui-reload.test.js')]);
  run('e2e: upload filename stored on storyline', 'node', [path.join(__dirname, 'e2e-bookfile.test.js')]);
  run('e2e: word_forms lesson generation', 'node', [path.join(__dirname, 'e2e-word-forms.test.js')]);
  run('e2e: writing lesson type (PLAN §D4)', 'node', [path.join(__dirname, 'e2e-writing.test.js')]);
  run('e2e: script choice reaches the model (v76_h)', 'node', [path.join(__dirname, 'e2e-script-choice.test.js')]);
  run('e2e: synonyms context sentences', 'node', [path.join(__dirname, 'e2e-synonyms.test.js')]);
  run('e2e: LLM chapter split', 'node', [path.join(__dirname, 'e2e-chapter-split.test.js')]);
  run('e2e: re-create storyline lessons', 'node', [path.join(__dirname, 'e2e-recreate.test.js')]);
  run('e2e: comic panel text extraction (PLAN §2.4 Track A4 milestone 2, v85_k)', 'node', [path.join(__dirname, 'e2e-comic-extract.test.js')]);
  run('e2e: comic panel image DESCRIPTION — the lazy fallback (user request)', 'node', [path.join(__dirname, 'e2e-comic-describe.test.js')]);
  run('e2e: storyline artwork — comicPanelCount + /api/comic-thumb (user request)', 'node', [path.join(__dirname, 'e2e-storyline-artwork.test.js')]);
  run('e2e: backend RE-DETECTION — a late-starting Ollama is picked up (user request)', 'node', [path.join(__dirname, 'e2e-backend-recheck.test.js')]);
  run('e2e: storyline chapter management — reorder/split/add (user request)', 'node', [path.join(__dirname, 'e2e-storyline-chapters.test.js')]);
  run('e2e: comic chapter formation (PLAN §2.4 Track A4 milestone 3, v85_m)', 'node', [path.join(__dirname, 'e2e-comic-chapter.test.js')]);
  run('e2e: comic panel auto-detection (PLAN §2.4 Track A4 milestone 5, v85_o)', 'node', [path.join(__dirname, 'e2e-comic-detect.test.js')]);
  run('e2e: save-story syncs comicPanels for a single-panel chapter (v86_g)', 'node', [path.join(__dirname, 'e2e-save-story-comic-sync.test.js')]);
  run('e2e: story-qc/accept ALSO syncs comicPanels for a single-panel chapter (v86_r)', 'node', [path.join(__dirname, 'e2e-story-qc-accept-comic-sync.test.js')]);
  run('e2e: retranslate a story on demand, after a manual fix (v86_w)', 'node', [path.join(__dirname, 'e2e-retranslate-story.test.js')]);
  run('e2e: post-gen storyboard opt-in fix, book-job pipeline (v85_p)', 'node', [path.join(__dirname, 'e2e-postgen-storyboard-optin.test.js')]);
  run('e2e: post-gen analysis opt-in, mirroring postGenStoryboard (item W follow-up, v86_o)', 'node', [path.join(__dirname, 'e2e-postgen-analysis-optin.test.js')]);
  run('e2e: model picker + table-format + split-translation + provenance', 'node', [path.join(__dirname, 'e2e-models.test.js')]);
  run('e2e: GET /api/jobs — the aggregate jobs list (item U)', 'node', [path.join(__dirname, 'e2e-jobs-list.test.js')]);
  run('e2e: unfinished-project drafts (item R)', 'node', [path.join(__dirname, 'e2e-drafts.test.js')]);
  run('e2e: unfinished-project drafts — comic upload flow (item R follow-up)', 'node', [path.join(__dirname, 'e2e-drafts-comic.test.js')]);
  run('e2e: skipLessons — decoupling chaptering from lesson generation (user request)', 'node', [path.join(__dirname, 'e2e-skip-lessons.test.js')]);
} else {
  console.log('\n(skipping e2e tests: --quick)');
}

console.log('\n' + '='.repeat(50));
if (failures.length) { console.error(summaryLine(total, failures)); process.exit(1); }
console.log(summaryLine(total, failures));
