// unit-add-lesson-menu.test.js
// v78_j (user, screenshot) — the single-chapter "add lesson" menu offers the FULL suite.
//
// User: "please add the whole suit of possible lessons to this menu. We had been hiding grammar and
// conjugation lessons from this single chapter version of 'add lessons', let's bring them back."
//
// There was no gate — only an omission. Both are full registry types in `LESSON_TYPE_META`, with a
// builder, an editor branch and a translated label, and the storyline-wide arc has offered them all
// along via `ADD_LESSON_TYPES`. The single-chapter menus simply listed fewer.
//
// The real defect is structural and is what this file guards: **the option list is written out
// three times** — the progress-card menu (static markup), the library menu (a template literal) and
// `ADD_LESSON_TYPES` (the arc's tick-list). Three copies of one list is how they came to disagree,
// and adding two options to two of them fixes today's symptom without fixing that. So the assertion
// is AGREEMENT, not presence: whatever a type's availability is, the two add-lesson menus must say
// the same thing about it.
'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const { ROOT } = require('./lib-dom');

const html = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');

// Pull the <option value="..."> set out of a named <select>, by id for the static menu and by the
// templated id for the library one.
function optionsOf(selectMarker) {
  const at = html.indexOf(selectMarker);
  assert.ok(at > 0, `the select ${selectMarker} exists`);
  const end = html.indexOf('</select>', at);
  assert.ok(end > at, `${selectMarker} is closed`);
  const block = html.slice(at, end);
  return [...block.matchAll(/<option value="([a-z_]+)"/g)].map(m => m[1]);
}

const card = optionsOf('id="sial-fmt-lesson-card"');
const lib  = optionsOf('id="sial-fmt-${sid}"');

// ── 1. Both menus offer grammar and conjugation ─────────────────────────────
{
  for (const type of ['grammar', 'conjugation']) {
    assert.ok(card.includes(type), `the progress-card menu offers ${type}`);
    assert.ok(lib.includes(type), `the library menu offers ${type}`);
  }
  console.log('  grammar and conjugation are back in both single-chapter menus');
}

// ── 2. The two menus AGREE, apart from ONE documented exception ─────────────
// The structural claim. They are two hand-written copies of one list, so any difference is drift
// until someone argues otherwise. Exactly one difference survives that test:
//
//   `mixed` is card-only. Its handler needs an OPEN LESSON SET — `if (!lessonCard || !d ||
//   !Array.isArray(d.lessons)) throw new Error(t('mixed.need_open_set'))` — because a mixed lesson
//   is a reference that pools the open set's other lessons at play time. Offering it from the
//   library menu would show an option that always fails.
//
// Encoding it here rather than dropping the assertion is the point: a NEW difference still fails,
// and if `mixed` ever becomes reachable from the library, this exception is the thing to delete.
{
  const CARD_ONLY = new Set(['mixed']);
  const cardSet = new Set(card), libSet = new Set(lib);
  const onlyCard = [...cardSet].filter(v => !libSet.has(v));
  const onlyLib  = [...libSet].filter(v => !cardSet.has(v));
  assert.deepStrictEqual(onlyLib, [],
    `the library menu offers nothing the card menu lacks (got ${JSON.stringify(onlyLib)})`);
  assert.deepStrictEqual(onlyCard.sort(), [...CARD_ONLY].sort(),
    'the ONLY card-only type is `mixed`, which needs an open lesson set — ' +
    `got ${JSON.stringify(onlyCard)}`);
  // And the exception is real, not a comment: the handler must actually guard it.
  assert.ok(/fmt === 'mixed'[\s\S]{0,400}mixed\.need_open_set/.test(html),
    'the mixed handler really does require an open lesson set — otherwise the exception above is ' +
    'an excuse rather than a reason');
  console.log(`  the two menus agree on ${libSet.size} types; \`mixed\` is card-only, and the handler proves why`);
}

// ── 3. Every offered type is a real, buildable lesson type ──────────────────
// An option whose value has no builder produces a menu entry that does nothing — worse than a
// missing one, because the learner asks for it and gets silence.
{
  const meta = html.slice(html.indexOf('const LESSON_TYPE_META'), html.indexOf('const LESSON_TYPE_META') + 4000);
  const known = new Set([...meta.matchAll(/^\s{2}([a-z_]+):\s*\{/gm)].map(m => m[1]));
  // `standard` is not a registry type — it is this chapter's own vocabulary, generated by
  // generateOneLesson rather than a registry builder (the ADD_LESSON_TYPES comment says so).
  const exempt = new Set(['standard']);
  assert.ok(known.size >= 8, `the registry was parsed (${known.size} types found)`);
  for (const v of card) {
    if (exempt.has(v)) continue;
    assert.ok(known.has(v), `"${v}" offered by the menu is a real registry type with a builder`);
  }
  console.log(`  all ${card.length} offered types are buildable (registry has ${known.size})`);
}

// ── 4. Non-vacuity: the parser really found options ─────────────────────────
// Without this, a changed markup shape would make §1–§3 pass over empty lists.
{
  assert.ok(card.length >= 8, `the card menu parsed a real list (${card.length} options)`);
  assert.ok(lib.length >= 8, `the library menu parsed a real list (${lib.length} options)`);
  assert.ok(card.includes('standard') && card.includes('math'),
    'the parse found the options that were there before this change, too');
  console.log('  both lists parsed non-trivially');
}

console.log('unit-add-lesson-menu: ALL PASSED');
